# Generated by Django 2.2.6 on 2020-09-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200917_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='unique_ingredient',
        ),
    ]
